//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contas()
        {
            this.Movimentos_contas = new HashSet<Movimentos_contas>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Tipo { get; set; }
        public int Banco_numero { get; set; }
        public string Nome_banco { get; set; }
        public string Conta { get; set; }
        public string Titular { get; set; }
        public string Agencia { get; set; }
        public string Convenio { get; set; }
        public string Carteira { get; set; }
        public string Nosso_numero { get; set; }
        public bool Inativa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentos_contas> Movimentos_contas { get; set; }
    }
}
