//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos_fiscais
    {
        public int Id { get; set; }
        public string Chave_acesso { get; set; }
        public int Tipo_documento { get; set; }
        public int Tipo_emissao { get; set; }
        public int Modelo { get; set; }
        public int Serie { get; set; }
        public int Lote { get; set; }
        public System.DateTime Data_emissao { get; set; }
        public int Ambiente { get; set; }
        public string Protocolo_autorizacao { get; set; }
        public string Protocolo_denegado { get; set; }
        public int Codigo_status { get; set; }
        public string Descricao_status { get; set; }
        public System.DateTime Data_autorizacao { get; set; }
        public bool Cancelado { get; set; }
        public Nullable<bool> Data_cancelamento { get; set; }
        public string Protocolo_cancelamento { get; set; }
        public bool Inutilizado { get; set; }
        public Nullable<System.DateTime> Data_inutilizacao { get; set; }
    }
}
