//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades_produtos
    {
        public string Identificador { get; set; }
        public int Produto_id { get; set; }
        public int Tamanho_id { get; set; }
        public int Cor_id { get; set; }
    
        public virtual Cores Cores { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Tamanhos Tamanhos { get; set; }
    }
}
