//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itens_pedido
    {
        public int Id { get; set; }
        public int Pedido_id { get; set; }
        public int Produto_id { get; set; }
        public string Lote { get; set; }
        public string Sublote { get; set; }
        public decimal Quant { get; set; }
        public decimal Valor_unit { get; set; }
        public decimal Aliquota { get; set; }
        public decimal Desconto { get; set; }
        public decimal Acrescimo { get; set; }
        public decimal Frete { get; set; }
        public decimal Outros_valores { get; set; }
        public int Cfop { get; set; }
        public int Vendedor_id { get; set; }
        public decimal Valor_final { get; set; }
        public int Unidade_id { get; set; }
        public string Grade_id { get; set; }
    
        public virtual Pedidos_venda Pedidos_venda { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
