//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamentos_financeiros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lancamentos_financeiros()
        {
            this.Pagamentos_lancamentos = new HashSet<Pagamentos_lancamentos>();
        }
    
        public int Id { get; set; }
        public int Conta_id { get; set; }
        public System.DateTime Data { get; set; }
        public int Tipo { get; set; }
        public int Plano_conta_id { get; set; }
        public int Origem { get; set; }
        public int Movimento_caixa_id { get; set; }
        public string Num_documento { get; set; }
        public decimal Valor_original { get; set; }
        public decimal Desconto { get; set; }
        public decimal Acrescimo { get; set; }
        public decimal Valor_final { get; set; }
        public int Usuario_id { get; set; }
        public int Cliente_id { get; set; }
        public int Fornecedor_id { get; set; }
        public string Descricao { get; set; }
        public int Parcela_id { get; set; }
        public decimal Despesas_acessorias { get; set; }
    
        public virtual Contas Contas { get; set; }
        public virtual Planos_contas Planos_contas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamentos_lancamentos> Pagamentos_lancamentos { get; set; }
    }
}
