//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimentos()
        {
            this.Itens_movimento = new HashSet<Itens_movimento>();
            this.Itens_pagamento = new HashSet<Itens_pagamento>();
        }
    
        public int Id { get; set; }
        public int Loja_id { get; set; }
        public System.DateTime Data { get; set; }
        public int Usuario_id { get; set; }
        public int Cliente_id { get; set; }
        public int Fornecedor_id { get; set; }
        public int Documento_id { get; set; }
        public int Tipo_movimento_id { get; set; }
        public bool Trocou_vendedor { get; set; }
        public int Caixa_id { get; set; }
    
        public virtual Caixas Caixas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itens_movimento> Itens_movimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itens_pagamento> Itens_pagamento { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
