//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcelas
    {
        public int Id { get; set; }
        public int Movimento_id { get; set; }
        public int Tipo_parcela { get; set; }
        public int Tipo_entidade { get; set; }
        public int Cliente_id { get; set; }
        public int Operadora_cartao_id { get; set; }
        public int Fornecedor_id { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Vencimento { get; set; }
    }
}
