//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarejoSimples.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos_fornecedores
    {
        public int Id { get; set; }
        public int Produto_id { get; set; }
        public int Fornecedor_id { get; set; }
        public int Unidade_id { get; set; }
        public decimal Fator_conversao { get; set; }
        public decimal Comissao { get; set; }
        public decimal Preco_custo { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Unidades Unidades { get; set; }
    }
}
